"""rename seller to staff, delete the relationship between staff and product

Revision ID: 000eed86bc11
Revises: 5212cd0e0af6
Create Date: 2024-12-25 19:58:23.774502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000eed86bc11'
down_revision = '5212cd0e0af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    if 'staff' not in inspector.get_table_names():
        op.create_table('staff',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('password', sa.String(length=64), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
        )
    if 'sellers' in inspector.get_table_names():
        op.drop_table('sellers')
    with op.batch_alter_table('products', schema=None) as batch_op:
        if 'fk_products_seller_id_sellers' in inspector.get_foreign_keys('products'):
            batch_op.drop_constraint('fk_products_seller_id_sellers', type_='foreignkey')
        if 'seller_id' in inspector.get_columns('products'):
            batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'sellers', ['seller_id'], ['id'])

    op.create_table('sellers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_sellers_username')
    )
    op.drop_table('staff')
    # ### end Alembic commands ###
