"""delete address is_default

Revision ID: 535725891e72
Revises: c3d63a159131
Create Date: 2024-12-28 18:06:02.213861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535725891e72'
down_revision = 'c3d63a159131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
