"""add sth for refund and return

Revision ID: 84b2317fe5df
Revises: b2c465420ccb
Create Date: 2024-12-28 23:42:14.745196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b2317fe5df'
down_revision = 'b2c465420ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('refund_reject_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('refund_reject_reason')
        batch_op.drop_column('refund_accepted')

    # ### end Alembic commands ###
