"""add soft delete

Revision ID: b2c465420ccb
Revises: 58bc17c0de4b
Create Date: 2024-12-28 23:14:45.114939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c465420ccb'
down_revision = '58bc17c0de4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
    
    op.execute('UPDATE orders SET is_deleted = False WHERE is_deleted IS NULL')
    
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('is_deleted', nullable=False)

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
