""".

Revision ID: c17e580d12f6
Revises: 9712ceea4834
Create Date: 2024-12-23 21:36:37.170007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17e580d12f6'
down_revision = '9712ceea4834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
