"""many to many relationship between address and customer

Revision ID: c3d63a159131
Revises: 84fcd53df198
Create Date: 2024-12-28 15:10:56.897855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d63a159131'
down_revision = '84fcd53df198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_address',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'address_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'addresses', ['address_id'], ['id'])

    op.drop_table('customer_address')
    # ### end Alembic commands ###
