"""add relationship table between categories and products

Revision ID: c90b647f20e6
Revises: 000eed86bc11
Create Date: 2024-12-26 18:04:05.963069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90b647f20e6'
down_revision = '000eed86bc11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('category_id')

    op.create_table(
        'product_category',
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_category_product_id'),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_product_category_category_id'),
        sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_category')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_products_category_id', 'categories', ['category_id'], ['id'])
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###
